"""empty message

Revision ID: 0f2eecf257ce
Revises: 86d0091607f6
Create Date: 2021-08-09 16:08:50.390242

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0f2eecf257ce"
down_revision = "86d0091607f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    # op.alter_column('events', 'isStated',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    op.add_column(
        "users",
        sa.Column(
            "userProfilePic", sa.String(length=256), server_default="", nullable=False
        ),
    )
    op.create_unique_constraint(None, "users", ["userEmail"])
    op.create_unique_constraint(None, "users", ["userPass"])
    ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "userProfilePic")
    # op.alter_column('events', 'isStated',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    # ### end Alembic commands ###
