"""empty message

Revision ID: 3e2fefdcb0be
Revises: 5c04880a4dfc
Create Date: 2021-03-27 14:51:27.058039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2fefdcb0be'
down_revision = '5c04880a4dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('users',
    # sa.Column('userId', sa.Integer(), nullable=False),
    # sa.Column('userFirstName', sa.String(length=30), nullable=False),
    # sa.Column('userLastName', sa.String(length=30), nullable=False),
    # sa.Column('userOrg', sa.String(length=30), nullable=True),
    # sa.Column('userRank', sa.String(length=30), nullable=False),
    # sa.Column('userEmail', sa.String(length=50), nullable=False),
    # sa.Column('userPass', sa.String(length=128), nullable=False),
    # sa.Column('user2FAEnabled', sa.Integer(), server_default='0', nullable=False),
    # sa.Column('user2FAKey', sa.String(length=32), server_default='', nullable=True),
    # sa.Column('userLoginFails', sa.Integer(), server_default='0', nullable=False),
    # sa.Column('userLoginLock', sa.Integer(), server_default='0', nullable=False),
    # sa.Column('userPermissions', sa.String(length=128), server_default='viewer', nullable=False),
    # sa.PrimaryKeyConstraint('userId'),
    # sa.UniqueConstraint('user2FAKey'),
    # sqlite_autoincrement=True
    # )
    # op.drop_table('sqlite_sequence')
    # op.alter_column('events', 'isStated',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('events', 'isStated',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    # op.drop_table('users')
    # ### end Alembic commands ###
    pass
