"""empty message

Revision ID: 5c04880a4dfc
Revises: ba790844e928
Create Date: 2021-03-26 02:52:31.023136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c04880a4dfc'
down_revision = 'ba790844e928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands ng_type=sa.INTEGER(),auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
