"""empty message

Revision ID: 78316fff6a67
Revises: ed1bcaa46128
Create Date: 2021-03-19 03:31:16.302973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78316fff6a67'
down_revision = 'ed1bcaa46128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('sqlite_sequence',
    #sa.Column('name', sa.NullType(), nullable=True),
    #sa.Column('seq', sa.NullType(), nullable=True)
    #)
    # ### end Alembic commands ###
    pass