"""empty message

Revision ID: 86d0091607f6
Revises: 3e2fefdcb0be
Create Date: 2021-03-27 15:36:46.020058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d0091607f6'
down_revision = '3e2fefdcb0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    # op.alter_column('events', 'isStated',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.create_unique_constraint(None, 'users', ['userPass'])
    # op.create_unique_constraint(None, 'users', ['userEmail'])
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='unique')
    # op.drop_constraint(None, 'users', type_='unique')
    # op.alter_column('events', 'isStated',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    # # ### end Alembic commands ###
    pass
