"""empty message

Revision ID: 8d61483420c7
Revises: 78316fff6a67
Create Date: 2021-03-19 21:21:45.829259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d61483420c7'
down_revision = '78316fff6a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('sqlite_sequence')
    op.add_column('events', sa.Column('isStated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'isStated')
    #op.create_table('sqlite_sequence',
    #sa.Column('name', sa.NullType(), nullable=True),
    #sa.Column('seq', sa.NullType(), nullable=True)
    #)
    # ### end Alembic commands ###
