"""empty message

Revision ID: a7ca190bca74
Revises: ef9982bd320a
Create Date: 2021-08-09 19:04:59.013548

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a7ca190bca74"
down_revision = "ef9982bd320a"
branch_labels = None
depends_on = None

naming_convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "events", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.alter_column(
            "isStated",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            nullable=False,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["userEmail"])
        batch_op.drop_column("user2FAKey")
        batch_op.drop_column("userLoginFails")
        batch_op.drop_column("user2FAEnabled")
        batch_op.drop_column("userPass")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("userPass", sa.VARCHAR(length=128), nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "user2FAEnabled",
                sa.INTEGER(),
                server_default=sa.text("'0'"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "userLoginFails",
                sa.INTEGER(),
                server_default=sa.text("'0'"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "user2FAKey",
                sa.VARCHAR(length=32),
                server_default=sa.text("('')"),
                nullable=True,
            )
        )
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column("isStated", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
