"""empty message

Revision ID: ba790844e928
Revises: 2b1650d5c7f5
Create Date: 2021-03-25 21:35:59.364307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba790844e928'
down_revision = '2b1650d5c7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    # op.add_column('events', sa.Column('isEmailThanked', sa.Integer(), nullable=False, server_default="0"))
    # op.alter_column('events', 'isStated',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            )
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('events', 'isStated',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.drop_column('events', 'isEmailThanked')
    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    # ### end Alembic commands ###
    pass
