"""empty message

Revision ID: ef9982bd320a
Revises: 0f2eecf257ce
Create Date: 2021-08-09 19:02:07.686327

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef9982bd320a"
down_revision = "0f2eecf257ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    # op.alter_column('events', 'isStated',
    #           existing_type=sa.INTEGER(),
    #           nullable=False)
    # op.add_column('users', sa.Column('userProfilePic', sa.String(length=128), nullable=True))
    # op.create_unique_constraint(None, 'users', ['userEmail'])
    # op.drop_column('users', 'user2FAKey')
    # op.drop_column('users', 'user2FAEnabled')
    # op.drop_column('users', 'userPass')
    # op.drop_column('users', 'userLoginFails')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "userLoginFails",
            sa.INTEGER(),
            server_default=sa.text("'0'"),
            nullable=False,
        ),
    )
    op.add_column(
        "users", sa.Column("userPass", sa.VARCHAR(length=128), nullable=False)
    )
    op.add_column(
        "users",
        sa.Column(
            "user2FAEnabled",
            sa.INTEGER(),
            server_default=sa.text("'0'"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "user2FAKey",
            sa.VARCHAR(length=32),
            server_default=sa.text("('')"),
            nullable=True,
        ),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "userProfilePic")
    # op.alter_column('events', 'isStated',
    #           existing_type=sa.INTEGER(),
    #           nullable=True)
    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    # ### end Alembic commands ###
